"""Optional YouTube cookie support.

Some networks and accounts get a bot-check or "sign in to confirm you're
not a robot" response from YouTube, which makes both search and download
fail even though nothing is wrong with the app. The standard fix is to let
yt-dlp send the same session cookies your browser already has.

This module takes whatever a person pastes from a browser cookie-export
extension (Cookie-Editor and similar tools export a JSON array; some tools
export the older Netscape cookies.txt format directly) and turns it into a
Netscape-format cookie file, since that's the one format both yt-dlp and
Python's own cookie jar can load directly.

Everything here stays on disk under the user's own XDG data directory and
is never transmitted anywhere except to youtube.com by yt-dlp/requests
themselves -- exactly like a browser would.
"""

from __future__ import annotations

import http.cookiejar
import json
import os
import re
import shutil
import tempfile
import time
from pathlib import Path

from core.paths import COOKIES_FILE, COOKIES_RAW_FILE, ensure_directories

NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# Generated by iSpotify -- do not share this file.\n"


class CookieError(ValueError):
    """The pasted text could not be understood as cookies."""


class CookieValidationError(CookieError):
    """The export was readable, but could not be verified with YouTube."""


YOUTUBE_DOMAINS = ("youtube.com", "google.com", "googleusercontent.com")
LOGIN_COOKIE_NAMES = {
    "SID", "HSID", "SSID", "APISID", "SAPISID", "LOGIN_INFO",
    "__Secure-1PSID", "__Secure-3PSID", "__Secure-1PAPISID",
    "__Secure-3PAPISID",
}
YOUTUBE_PLAYER_CLIENTS = ["default", "web_embedded"]


def _looks_like_netscape(text: str) -> bool:
    for line in text.splitlines():
        line = line.strip()
        if not line or (line.startswith("#") and not line.startswith("#HttpOnly_")):
            continue
        return len(line.split("\t")) >= 7
    return False


def _netscape_line(cookie: dict) -> str | None:
    domain = (cookie.get("domain") or "").strip()
    name = cookie.get("name")
    value = cookie.get("value")
    if not domain or not name or value is None:
        return None
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path") or "/"
    secure = "TRUE" if cookie.get("secure") else "FALSE"
    if cookie.get("session"):
        expiry = 0
    else:
        raw_expiry = cookie.get("expirationDate") or cookie.get("expires") or 0
        try:
            expiry = int(round(float(raw_expiry)))
        except (TypeError, ValueError):
            expiry = 0
    return "\t".join([domain, include_subdomains, path, secure, str(expiry), name, str(value)])


def _from_json(text: str) -> tuple[str, int, list[dict]]:
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise CookieError(f"That doesn't look like valid JSON ({exc}).") from exc
    if isinstance(data, dict):
        # Some export tools wrap the array as {"cookies": [...]}.
        data = data.get("cookies", [])
    if not isinstance(data, list) or not data:
        raise CookieError("Expected a JSON array of cookie objects.")
    lines = []
    parsed = []
    for entry in data:
        if not isinstance(entry, dict):
            continue
        line = _netscape_line(entry)
        if line:
            lines.append(line)
            parsed.append(entry)
    if not lines:
        raise CookieError(
            "No usable cookies found -- each entry needs at least "
            "domain, name, and value."
        )
    return NETSCAPE_HEADER + "\n".join(lines) + "\n", len(lines), parsed


def _from_netscape(text: str) -> tuple[str, int, list[dict]]:
    lines = []
    parsed = []
    for source_line in text.splitlines():
        stripped = source_line.strip()
        if not stripped or (
            stripped.startswith("#") and not stripped.startswith("#HttpOnly_")
        ):
            continue
        fields = source_line.split("\t")
        if len(fields) < 7:
            raise CookieError(
                "A cookies.txt row is malformed; expected 7 tab-separated fields."
            )
        domain, _subdomains, path, secure, expiry, name = fields[:6]
        parsed_domain = domain.removeprefix("#HttpOnly_")
        value = "\t".join(fields[6:])
        try:
            expiry_value = int(float(expiry or 0))
        except ValueError as exc:
            raise CookieError(f"Cookie {name!r} has an invalid expiry time.") from exc
        lines.append("\t".join(fields))
        parsed.append({
            "domain": parsed_domain,
            "path": path,
            "secure": secure.upper() == "TRUE",
            "expirationDate": expiry_value,
            "session": expiry_value == 0,
            "name": name,
            "value": value,
        })
    if not lines:
        raise CookieError("No usable cookie rows were found.")
    return NETSCAPE_HEADER + "\n".join(lines) + "\n", len(lines), parsed


def _parse(text: str) -> tuple[str, int, list[dict]]:
    text = (text or "").strip()
    if not text:
        raise CookieError("Paste your exported cookies first.")
    if _looks_like_netscape(text):
        return _from_netscape(text)
    return _from_json(text)


def _validate_cookie_set(entries: list[dict]) -> None:
    now = time.time()

    def is_youtube_domain(value: str) -> bool:
        host = (value or "").lower().lstrip(".")
        return any(host == domain or host.endswith(f".{domain}") for domain in YOUTUBE_DOMAINS)

    relevant = [
        item for item in entries
        if is_youtube_domain(item.get("domain") or "")
    ]
    if not relevant:
        raise CookieValidationError(
            "This export contains no YouTube or Google cookies. Export cookies "
            "while youtube.com is open and you are signed in."
        )

    live_login = []
    for item in relevant:
        if item.get("name") not in LOGIN_COOKIE_NAMES or not item.get("value"):
            continue
        raw_expiry = item.get("expirationDate") or item.get("expires") or 0
        try:
            expiry = float(raw_expiry)
        except (TypeError, ValueError):
            expiry = 0
        if item.get("session") or expiry == 0 or expiry > now:
            live_login.append(item)
    if not live_login:
        raise CookieValidationError(
            "The export has no live YouTube sign-in cookies. Sign in again, "
            "refresh youtube.com, and create a new export."
        )


def validate_cookie_text(text: str) -> None:
    """Perform fast local checks suitable for immediate UI feedback."""
    _body, _count, entries = _parse(text)
    _validate_cookie_set(entries)


def _write_atomic(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}-", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(value)
        try:
            os.chmod(temp_name, 0o600)
        except OSError:
            pass
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def save_cookies(text: str) -> int:
    """Parse and persist pasted cookies. Returns how many were saved.

    Raises CookieError if the text isn't a format this app understands.
    """

    body, count, _entries = _parse(text)
    ensure_directories()
    _write_atomic(COOKIES_FILE, body)
    _write_atomic(COOKIES_RAW_FILE, text.strip())
    return max(count, 0)


def validate_and_save_cookies(text: str) -> tuple[int, str]:
    """Verify the real YouTube session, then save it atomically.

    Cookie validity is intentionally tested against YouTube's signed-in page,
    not against a hard-coded video. YouTube's authenticated player can return
    "The page needs to be reloaded" for valid sessions, which is an upstream
    playback problem rather than evidence that the cookies are invalid.
    """

    body, count, entries = _parse(text)
    _validate_cookie_set(entries)

    fd, candidate_name = tempfile.mkstemp(
        prefix="ispotify-cookie-test-", suffix=".txt"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        try:
            os.chmod(candidate_name, 0o600)
        except OSError:
            pass
        _verify_youtube_session(Path(candidate_name))
    finally:
        try:
            os.unlink(candidate_name)
        except OSError:
            pass

    ensure_directories()
    _write_atomic(COOKIES_FILE, body)
    _write_atomic(COOKIES_RAW_FILE, text.strip())
    return count, ""


def _verify_youtube_session(cookie_file: Path) -> None:
    import requests

    jar = http.cookiejar.MozillaCookieJar(str(cookie_file))
    try:
        jar.load(ignore_discard=True, ignore_expires=False)
    except (OSError, http.cookiejar.LoadError) as exc:
        raise CookieValidationError(
            "The cookie file could not be loaded after conversion."
        ) from exc

    try:
        response = requests.get(
            "https://www.youtube.com/feed/library",
            headers={
                "User-Agent": (
                    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                    "Chrome/128.0 Safari/537.36"
                ),
                "Accept-Language": "en-US,en;q=0.9",
            },
            cookies=jar,
            timeout=15,
            allow_redirects=True,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        raise CookieValidationError(
            "YouTube could not be reached to test these cookies. Check your "
            "connection and try again."
        ) from exc

    page = response.text
    signed_in = bool(re.search(r'"LOGGED_IN"\s*:\s*true', page, re.IGNORECASE))
    login_wall = (
        "accounts.google.com" in response.url
        or "ServiceLogin" in response.url
        or '"LOGGED_IN":false' in page
    )
    if login_wall or not signed_in:
        raise CookieValidationError(
            "YouTube did not accept this as a signed-in session. The cookies "
            "may be expired, incomplete, or exported from the wrong site."
        )


def ydl_youtube_compat_kwargs() -> dict:
    """Current resilient YouTube client selection for authenticated requests.

    The normal logged-in ``tv_downgraded`` client currently returns
    "The page needs to be reloaded" for valid sessions. Explicitly selecting
    the default and embedded clients follows yt-dlp's upstream workaround and
    keeps validation and real downloads on the same path.
    """
    options = {
        "extractor_args": {
            "youtube": {"player_client": list(YOUTUBE_PLAYER_CLIENTS)}
        }
    }
    runtime = _find_javascript_runtime()
    if runtime:
        name, path = runtime
        options["js_runtimes"] = {name: {"path": str(path)}}
    return options


def _find_javascript_runtime() -> tuple[str, Path] | None:
    """Find a yt-dlp-compatible JS runtime without assuming one installer.

    Deno is preferred. Node is a reliable fallback when it is new enough;
    common Windows/Linux locations and Codex's bundled runtime are checked in
    addition to PATH so the desktop launcher sees the same tools as a shell.
    """
    suffix = ".exe" if os.name == "nt" else ""
    candidates = []
    for name in ("deno", "node"):
        found = shutil.which(name)
        if found:
            candidates.append((name, Path(found)))

    candidates.extend([
        ("deno", Path.home() / ".deno" / "bin" / f"deno{suffix}"),
        ("node", Path(os.environ.get("ProgramFiles", "C:/Program Files"))
         / "nodejs" / f"node{suffix}"),
        ("node", Path.home() / ".cache" / "codex-runtimes"
         / "codex-primary-runtime" / "dependencies" / "node" / "bin"
         / f"node{suffix}"),
    ])
    seen = set()
    for name, path in candidates:
        normalized = str(path).casefold()
        if normalized in seen:
            continue
        seen.add(normalized)
        if path.is_file():
            return name, path
    return None


def load_saved_text() -> str:
    if COOKIES_RAW_FILE.exists():
        try:
            return COOKIES_RAW_FILE.read_text(encoding="utf-8")
        except OSError:
            return ""
    return ""


def is_configured() -> bool:
    return COOKIES_FILE.exists() and COOKIES_FILE.stat().st_size > 0


def status_text() -> str:
    if not is_configured():
        return "No cookies saved yet"
    try:
        count = sum(
            1 for line in COOKIES_FILE.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        )
        age_minutes = int((time.time() - COOKIES_FILE.stat().st_mtime) / 60)
    except OSError:
        return "Cookies saved"
    if age_minutes < 1:
        when = "just now"
    elif age_minutes < 60:
        when = f"{age_minutes} min ago"
    else:
        when = f"{age_minutes // 60}h ago"
    return f"{count} cookies saved · updated {when}"


def clear_cookies() -> None:
    for path in (COOKIES_FILE, COOKIES_RAW_FILE):
        try:
            path.unlink(missing_ok=True)
        except OSError:
            pass


def ydl_cookie_kwargs() -> dict:
    """Extra yt-dlp options to include when cookies are configured."""
    if is_configured():
        return {"cookiefile": str(COOKIES_FILE)}
    return {}


def load_requests_cookiejar() -> http.cookiejar.MozillaCookieJar | None:
    """A cookie jar for the plain `requests` calls search uses directly."""
    if not is_configured():
        return None
    jar = http.cookiejar.MozillaCookieJar(str(COOKIES_FILE))
    try:
        jar.load(ignore_discard=True, ignore_expires=True)
    except (OSError, http.cookiejar.LoadError):
        return None
    return jar
